# Generated by Django 4.2.16 on 2024-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredefinedQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("query", models.TextField()),
                ("placeholder_1", models.TextField()),
                ("placeholder_2", models.TextField()),
                ("settings", models.JSONField()),
            ],
        ),
    ]
