# Generated by Django 4.2.16 on 2025-01-30 16:06
from django.db import migrations

def create_additional_predefined_queries(apps, schema_editor):
    # Get the model using apps.get_model (important for migrations)
    PredefinedQuery = apps.get_model('api', 'PredefinedQuery')

    # Create the new predefined query instance
    PredefinedQuery.objects.create(
        name="Generate Hierarchy",
        query="""
            LET node = DOCUMENT('@value1', '@value2')
            RETURN { nodes: [node] }
        """,
        placeholder_1="Enter collection (CL, etc.)...",
        placeholder_2="Enter id (0000077)...",
        settings={
            "defaultDepth": 5,
            "collectionsToAllow": [
                '@value1'
            ],
            "labelStates": {
                ".collection-label": False,
                ".link-label": True,
                ".node-label": True,
            },
            "edgeDirection": "INBOUND"
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_predefined_queries'),  # Ensure this points to the last migration
    ]

    operations = [
        migrations.RunPython(create_additional_predefined_queries),
    ]

